apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: service-binding
spec:
  applicationSelector:
    group: apps
    resource: deployments
    resourceRef: sample-service-binding-postgresql
    version: v1
  backingServiceSelector:
    group: postgresql.baiju.dev
    kind: Database
    resourceRef: demo-database
    version: v1alpha1
  detectBindingResources: true
  envVarPrefix: postgresql
  